source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Test_Example', :exclusive => true do
  pod 'Test', :path => '../'
end

target 'Test_Tests', :exclusive => true do
  pod 'Test', :path => '../'

  
end
